### ISSUE TITLE
Measure gaps in USVs

### ISSUE THREAD

**Issue by VoiceScientist** [DrCoffey/DeepSqueak#147]
**Is your feature request related to a problem? Please describe.**
We are measuring USVs that have gaps - moments that are not detected in the contour because the call drops out. 

**Describe the solution you'd like**
We'd like a way to quantify this broken/inconsistent appearance

**Describe alternatives you've considered**
Is there a way to calculate the duration of the detected points on the contour relative to the duration of the call? Or perhaps count the number of noncontiguous points on the contour?

**Additional context**
Screenshot of sample "broken" USV attached
![Broken_USV](https://user-images.githubusercontent.com/40209597/148424010-6db9477c-f3b6-4897-934c-df68d43a5a9c.png)
.

**Comment by DrCoffey** [comment]
Hey, sorry for the slow reply.

There isn't an easy way to do this with DeepSqueak, but I think the information could be pulled out of the extracted contours.

If you run unsupervised clustering and save the extracted contours you should be able to load that file into matlab and look at the contours for every single call. There should be a time and frequency variable for every contour, so you would have to write a quick script to determine how many gaps there are. You would also have to pick some time threshold, so that missing a single sample doesn't count as a gap.

On a separate note, your recordings look beautiful, can I ask what mics or recording setup you are using?

-Kevin

**Comment by VoiceScientist** [comment]
No problem about the delay - I appreciate your ongoing development and support of DeepSqueak. The extracted contours aren't saved with a typical analysis? We'd need to run the clustering? 

Glad you like our recordings. We're using Avisoft hardware (CM16/CMPA mic with the UltraSoundGate 816H interface) and we record in a walk-in sound booth with the animal in a sound-treated cubicle (https://www.coulbourn.com/product_p/h10-24a.htm).

**Comment by DrCoffey** [comment]
Ya, if you run clustering you can extract all of the contours at once. You don't have to complete clustering, you can quit out after you extract and save the contours.
