### ISSUE TITLE
single call detected as multiple calls 

### ISSUE THREAD

**Issue by sulafafakhreddin** [DrCoffey/DeepSqueak#159]
How do i automatically set deepsqueak to stop detecting a single call as multiple calls

**Comment by DrCoffey** [comment]
Hey @sulafafakhreddin, Can you show me an example?

**Comment by ARTUR551** [comment]
Hi DrCoffey,

Related to this issue:
What is the default minimal interval that DeepSqueak uses to distinguish one vocalization of the next one?
Is there a way to change it?

Thanks in advance!

A.

**Comment by DrCoffey** [comment]
@ARTUR551 There isn't any default minimal interval. DeepSqueak uses machine vision instead of specific rules. If any two detection boxes overlap in time they will be combined. If they don't it will be considered 2 calls. Practically, boxes usually extend 5ms or so past a call, so things within 5ms usually are boxed as the same call.

**Comment by DrCoffey** [comment]
Actually there is a hidden function that would allow you to merge boxes within a certain interval.  

If you change line 49 in merge_Callback.m 

from:
Calls = merge_boxes(AllBoxes, AllScores .* AllAccept, AllClass, audio_info, 1, 0, 0);

to:
Calls = merge_boxes(AllBoxes, AllScores .* AllAccept, AllClass, audio_info, 1, 0, 1);

It will turn on box padding. 

Then you can set the padding number in line 58 of merge_boxes.m
    timeExpansion = .1; % Change this to whatever interval you want.

Then if you run Tools->Merge Boxes, it will pad all of the boxes and merge any that overlap.

**Comment by ARTUR551** [comment]
Thanks for the clarification!

Best,

A.
