### ISSUE TITLE
New error 

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#16]
Getting the following error after changing line 86 of Squeakdetect function to "im = mat2gray(s,[med*.75 med*15]);"

Error using horzcat
Dimensions of arrays being concatenated are not consistent.

Error in SqueakDetect (line 228)
    audio=[pad, audio];

Error in multinetdect_Callback (line 96)
            Calls=SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
Error while evaluating UIControl Callback.

**Comment by MxMarx** [comment]
I have replicated and fixed this error.

The error resulted from detecting a call at the very beginning of an audio file. We take the audio from the call itself along with some padding before and after the call. If a call occurs at the beginning of the file, there isn't any audio before the call, so we pad the audio with zeros.

It looks like we accidentally concatenated the audio and the zero padding horizontally instead of vertically, so I replaced a comma with a semicolon, and now it works properly (at least for me).
