### ISSUE TITLE
Poor detection with low intensity and step USVs

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#20]
I am having difficulty getting good contour detection with low intensity and step USVs. 
For example, with this USV, half the USV is not detected.
![usv_01_low](https://user-images.githubusercontent.com/45463545/50994257-ce255780-14e9-11e9-8fd8-67a717a0176d.PNG)

Also, for most step USVs that have a small high or low beginning/end, the step is not included in the contour.
![usv_02_step](https://user-images.githubusercontent.com/45463545/50994334-03ca4080-14ea-11e9-9e32-517f58b97759.PNG)
Changing the contour threshold from .25 to .2 will improve contour but then I need to redraw every single box. 

I have already increased gain by changing line 89 in squeakdetect.m to  "im = mat2gray(s,[med*.75 [med*15]);"]

Any suggestions to improve contour?

**Comment by cmlenell1** [comment]
Also, with step vocalizations (both step-up and step-down) like the second example, the contour detection sometimes picks up the step if I redraw the box so that the box is on top of the step part of the USV.

**Comment by DrCoffey** [comment]
The contour detection only works within the boxes. I think a lot of those calls are so quiet that they are pushing the signal to noise limits on our detection network. You can play with the slider next to the tonality graph to optimize contouring.

One option to help with picking up the steps is to expand all of the boxes vertically. We didn't do that initially because it could grab low frequency noise, but we can try to add a tool that lets you make all boxes extend from 30-90 khz. It might take us a minute to get around to it.

**Comment by MxMarx** [comment]
I've added a function to set the upper and/or lower frequency of each call to a constant value. If the boxes are at the right places in time, this might help with detecting steps outside of the box.

Its located under "Tools > Automatic Review > Set Static Box Height".

**Comment by DrCoffey** [comment]
Hey cmlenell1,

I think that is about all we can do with these low intensity calls. I'm going to close this issue, but feel free to open another.

-Kevin
