### ISSUE TITLE
Not detected, more faint calls 

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#23]
Hi there, thanks very much for writing such an amazing software!

I just have one issue when it comes to automatically detecting quite faint calls (see picture, the ones with green arrows are successfully detected but the ones with white arrows are not).

Is there a way to increase the detection sensitivity for an entire file rather than adjusting it for each box post detection? 

Or is there a way to later on add the missing calls and then train the network with these, so that future detections
![not_detected_calls](https://user-images.githubusercontent.com/36044114/51325465-41d8de80-1a6d-11e9-9bc3-453114f7829d.png)
 will take the faint calls also into account?

Thanks very much in advance,
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

We removed the gain setting feature in the early versions in an effort to automatically scale audio, so that DeepSqueak will work with any recording. Different labs we were beta testing with had 100 fold differences in volume.

That said, you can manually change the automatic scaling to try to boost up the faint calls.

Currently, line 89 in squeakdetect.m (in the functions folder) is **im = mat2gray(s,[med*.1 [med*30]);**

if you change that to something like **im = mat2gray(s,[med*.75 [med*15]);**
you can increase the brightness of quiet calls at the cost of dynamic range. You could play around with the numbers a little to maximize performance.

Let me know if that helps.

-Kevin

**Comment by DrCoffey** [comment]
Sorry, it is line 93 now!

**Comment by DrCoffey** [comment]
Something went wrong in the copy paste... here is the correct code.
old line       im = mat2gray(s,[med*.1 med*30]);
new line      im = mat2gray(s,[med*.75 med*15]);

**Comment by DrCoffey** [comment]
Ahhhhh, sorry again. Github auto formats stars to italics. Here is the correct code

```im = mat2gray(s,[med*.1 med*30]);```
```im = mat2gray(s,[med*.75 med*15]);```

**Comment by imgross** [comment]
Hi Kevin,

thanks for that piece of code. Now it works much better!

Do you in general advise to change that gain setting when coming across undetected calls or is there an additional way of marking/identifying the undetected ones (like manual marking or so)?

Best,
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

It is obviously not ideal to have to change the gain settings frequently. I would try and keep your recording volume consistent and then find the gain setting that works the best for you. That said, we are working on an update that will attempt to automatically determine the best gain settings (or even just use multiple settings on each file) at the cost of some speed. Keep an eye out, as DeepSqueak will tell you when the update is available when you load it. 

I am going to close this particular issue, but if you have any other problems feel free to open a new one.

-Kevin
