### ISSUE TITLE
Preciseness of setting bounding box around calls

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#25]
Hey,

I was wondering how precise one should be when it comes to (re)drawing the bounding box around a detected call? 

Is it important that there is not too much "no call" area inside the box or is simply important that the entire call with all its features sits inside this box no matter how much "non call" area is in there?

Thanks for your help!
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

It shouldn't matter how big the box is, as long as the whole call is contained. The contour detection will find  the extents of the call. The contour threshold can be adjusted with the slider that is next to the tonality display. Is there anything in  particular that isn't working for you?

-Kevin

**Comment by imgross** [comment]
Hi Kevin,

ok great that is good to know!

Sometimes I had the case that parts of the call were outside the box and when redrawing I was not sure how close the box is supposed to be around the particular call. But now this is clear.

Thanks very much,
Isa

**Comment by DrCoffey** [comment]
Ok Great! The new version of DeepSqueak also has a High Recall mode that might help box quieter parts of calls, but it is a little more susceptible to noise.

**Comment by LWilkinKrug** [comment]
Hi Kevin, 
I'd like to pick this one up, as we've found that changing the box changes the call information. What this means is that I'd to manually redraw every box to be tighter and with that reflect the actual call properties. 

The first screenshot shows a bigger box. Compare the call properties with the second screenshot below, where I've drawn a tighter box around the call

**Bigger box**
![big-box](https://user-images.githubusercontent.com/41356096/61837279-2b0dbb80-aed8-11e9-8a21-2614892b9d22.png)
**Tight box**
![tight-box](https://user-images.githubusercontent.com/41356096/61837281-2b0dbb80-aed8-11e9-9d23-e0850bf47fdc.png)

Whichever box I accept reflects what's exported.

**Comment by DrCoffey** [comment]
Hey LWilkinKrug,

The size of the box should not effect the call stats because they are based on the contour. The problem here is that you have the contour threshold set to zero (see red arrow). When the threshold is set to zero, every column in the box will get a contour value. That is why the contour includes the 40ish kHz noise band in both images. Slide the slider (red arrow) up to the green line, and then you shouldn't have to manually re-box anything!

![Tonality Threshold](https://user-images.githubusercontent.com/39605011/61901408-8dfd5380-aed4-11e9-84e2-41b8650edb18.png)

**Comment by LWilkinKrug** [comment]
Hi Kevin, 

That works! Thanks a million :)

LK
