### ISSUE TITLE
Seperate long mice calls

### ISSUE THREAD

**Issue by BavoKempen** [DrCoffey/DeepSqueak#33]
Dear Kevin and Russell,

I have been playing  for a while with the idea to ask you whether it would be possible to implement a function to adjust the post detection merging of boxes for calls that are split due to e.g. burst of noise or just less signal. Furthermore, I tried to play a bit with the FFT parameters in the "separatelongratcall.mat" function, however, no success. 
The way how I would see this implemented would be through manually implementing a value in ms to bind boxes together (e.g. 3ms), but still with the freedom to do so differently for each detection file (or all together) depending on the needs of the user.

Do you think it is feasible to implement a function as such?
If you would like me to explain more elaborately and provide some examples, I will gladly do so!
Curious to hear what you think.

Kind regards and thank you in advance,

Bavo Kempen

**Comment by MxMarx** [comment]
Hi Bavo,

A function like this might be possible in the future. Are the calls separated cleanly by tonality?

At the moment, DeepSqueak merges all overlapping boxes after detection. On line 22 of 
"functions/merge_boxes.m", we currently set it so that all boxes that overlap each other by a ratio of 0.15 are merged into a single box, because we previously has some issues with splits being put into seperate boxes. You could try raising this value so that it is more conservative when merging adjacent calls, maybe to 0.5.

Best,
Russell

**Comment by DrCoffey** [comment]
Hey Bavo,

We are running out of time to work on DeepSqueak, so we will not be doing many other feature changes. We will continue to try and implement bug fixes however. If you implement any better method of box merging be sure so send us a pull request, and we will check it out.
