### ISSUE TITLE
wav file not detected 

### ISSUE THREAD

**Issue by mschart** [DrCoffey/DeepSqueak#4]
Hi there,
I want to set the audio folder with a wav file but the wav file is not found:
![image](https://user-images.githubusercontent.com/17218515/47919816-aba30c80-deb0-11e8-9067-27aa8e9114d1.png)
Any idea?

**Comment by DrCoffey** [comment]
We made the mistake of using the "windows only" slash direction in our paths. We will fix it ASAP!

**Comment by DrCoffey** [comment]
We fixed the slashes, let us know if that solved your issue?

**Comment by mschart** [comment]
Hi,
Unfortunately not, still no wav file detected. I'm on Ubuntu 18.04, matlab R2017a, just cloned your scripts and tried.

**Comment by DrCoffey** [comment]
We just tried on a mac, and it all seems to be working, but we don't currently have a Linux machine. Do you get an error, or just "No Audio" in the menu? Try to make sure you are clicked into the folder before you click "open"

Finally, I am not sure that DeepSqueak will function on 2017a. We have only tested 2017b and latter.

**Comment by VoiceScientist** [comment]
I had some insidious problems initially because I didn’t have all the correct toolboxes installed. mschart, do you have all the following installed?

Required Matlab toolboxes: 
1) Computer Vision System Toolbox™
2) Curve Fitting Toolbox
3) Image Processing Toolbox™
4) Deep Learning Toolbox™ (formerly Neural Network Toolbox™)
5) Parallel Computing Toolbox™

**Comment by mschart** [comment]
Hi there,

Thanks for this. I have installed a newer matlab version an now the wav file is detected. Cheers!
