### ISSUE TITLE
Supervised classification error

### ISSUE THREAD

**Issue by stevenHH92** [DrCoffey/DeepSqueak#43]
Hey,
I was training the supervised classifier and wanted to conduct now the supervised classification, however the following error is now occurring:
I am using MATLAB R2018b.
"DeepSqueak version 2.6.0
Reference to non-existent field 'squeakfolder'.

Error in SupervisedClassification_Callback (line 6)
[FileName,PathName] = uigetfile(fullfile(handles.squeakfolder,'Clustering Models','*.mat'),'Select Network');

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('SupervisedClassification_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback."

Do you have an idea what is going wrong here?
Cheers,
Steven

**Comment by MxMarx** [comment]
That error sounds like it's caused by an older version of the file. Is it possible that you have multiple copies of the function? We reorganized the folders a while ago, so if you had an older version and updated it, the old files might still be there.

In the current version, line 6 of SupervisedClassification_Callback .m should be:
 ```[FileName,PathName] = uigetfile(fullfile(handles.data.squeakfolder,'Clustering Models','*.mat'),'Select Network');```

-Russell
