### ISSUE TITLE
Negative average power

### ISSUE THREAD

**Issue by LWilkinKrug** [DrCoffey/DeepSqueak#52]
I've been wondering why the average power is reported as a negative value. When looking at the [example in the Wiki](https://github.com/DrCoffey/DeepSqueak/wiki/main-window), I noticed that the value is reported as a positive. Is there something wrong with the way I run my analyses?

![Screenshot 2019-08-02 12 10 39](https://user-images.githubusercontent.com/41356096/62335224-1c9a5200-b51f-11e9-87a1-6e38642b0065.png)

**Comment by DrCoffey** [comment]
Hey,

It is negative because we changed from "power" to decibels. dBA is a relative scale, not a fixed scale and it can be a lttile odd... Most of the time 0 dB is the roughly softest a person can hear, and then it goes up on a log scale. However, 0 dB can also be set to the loudest thing and then most sounds will be negative dB. This is the case with most audio equipment.
 
Because we don't actually know the sound pressure, only the electrical reading from the microphone (every lab has different sensitivity mics/ different gain settings), we have to use the relative power values to calculate dB. If you are using different mics with different gain settings these numbers will not be comparable!

So don't worry that it is negative, it is still a "loudness" metric within your experiment, as long as your mics are all the same, with the exact same gain settings. We try and keep people away from using power in any meaningful fashion because it is hard to control the location of the animals with respect to the microphone.

Hopefully Russell sees this and chimes in if I missed something.

**Comment by LWilkinKrug** [comment]
Thanks for the explanation, Kevin
