### ISSUE TITLE
Trouble uploading .wav file

### ISSUE THREAD

**Issue by PhDcd** [DrCoffey/DeepSqueak#66]
I'm using MATLAB 2019B and DeepSqueak version 2.6.1.  I read that DeepSqueak is capable of reading WAV (.wav) files, so that is how I have saved audio files recorded in Audacity.  However, I cannot upload these .wav files to DeepSqueak.  Does DeepSqueak not allow for imports from Audacity?

**Comment by DrCoffey** [comment]
DeepSqueak should have no problem with .wav files from audacity.

Here is the Wiki for detection: https://github.com/DrCoffey/DeepSqueak/wiki/usv-detection

**Comment by PhDcd** [comment]
Thank you for your prompt response!
However, if I select go to "Import/Export" to import the Audio File, there are only options to import from Raven, Ultravox, MUPET, and X-BAT (See first screenshot).  If I try to import the audio file by selecting "Select Audio File," it will not allow me to click on the .wav file (please second screenshot).
<img width="580" alt="SS1" src="https://user-images.githubusercontent.com/58785213/70658671-6f51ec00-1c2c-11ea-9110-c490248ed37b.png">
<img width="580" alt="SS1" src="https://user-images.githubusercontent.com/58785213/70658675-711baf80-1c2c-11ea-8e93-de006bde74db.png">

**Comment by DrCoffey** [comment]
That is because you do not import .wav files. Those functions are for importing analysed files from other systems. Use "Select Audio Folder" to Add your .wav files to the drop down menu and begin detection. Please read the wiki for detailed instruction on how to analyse files.

https://github.com/DrCoffey/DeepSqueak/wiki/usv-detection

https://github.com/DrCoffey/DeepSqueak/wiki/selecting-audio-files

**Comment by PhDcd** [comment]
I apologize, my issue was I was trying to click the file not the folder. Thank you!
