### ISSUE TITLE
Slope definition

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#94]
Hi Dr. Coffey,

Could you explain how slope is calculated? It's hard for me to decipher from the code. 

Thanks!

Charlie

**Comment by DrCoffey** [comment]
Hey Charlie,

The slope calculation is Russell's code, so it is both elegant and difficult to understand :)  

The lines are in CalculateStats.m (82-88)

``` 
try
    X = [ones(length(stats.ridgeTime),1), TimeScale*stats.ridgeTime.'];
    ls = X \ (FreqScale*stats.ridgeFreq_smooth);
    stats.Slope = ls(2);
catch
    stats.Slope = 0;
end
```

The backslash is not a normal division symbol but the function [mldivide.](https://www.mathworks.com/help/matlab/ref/mldivide.html)

mldivide can solve for the least squares solution for the contour. Russell uses this instead DeltaFreq/DeltaTime because DeltaFreq is calculated as the maximum frequency change, and not the rise of a least squares line.

Hope that helps,
Kevin

**Comment by VoiceScientist** [comment]
Thanks for the reply, Kevin. Charlie and I are working on a manuscript together and are trying to make sure we describe the parameters appropriately. Would it be fair to say that the slope (kHz/s) is simply the slope of the least squares regression line fitted to the detected points in the contour?
Aaron

**Comment by DrCoffey** [comment]
Yes!
